const ALLOWED_MAJOR_CATEGORIES = [
  'A_pipeline_absorption',
  'B_margin_pressures',
  'C_funding_credit',
  'D_macro_regime'
];

const MAJOR_CATEGORY_LABELS = {
  A_pipeline_absorption: 'Pipeline & absorption',
  B_margin_pressures: 'Margin pressures',
  C_funding_credit: 'Funding & credit',
  D_macro_regime: 'Macro regime'
};

const EXPECTED_SERIES_IDS_49 = [
  'commind_business_park_planned_others',
  'commind_business_park_planned_provisional_permission',
  'commind_business_park_planned_written_permission',
  'commind_business_park_total',
  'commind_business_park_under_construction',
  'commind_office_planned_others',
  'commind_office_planned_provisional_permission',
  'commind_office_planned_written_permission',
  'commind_office_total',
  'commind_office_under_construction',
  'commind_retail_planned_others',
  'commind_retail_planned_provisional_permission',
  'commind_retail_planned_written_permission',
  'commind_retail_total',
  'commind_retail_under_construction',
  'industrial_pipeline_others',
  'industrial_pipeline_provisional_permission',
  'industrial_pipeline_total',
  'industrial_pipeline_under_construction',
  'industrial_pipeline_written_permission',
  'prp_pipeline_non_landed_planned_others',
  'prp_pipeline_non_landed_planned_provisional_permission',
  'prp_pipeline_non_landed_planned_written_permission',
  'prp_pipeline_non_landed_under_construction',
  'prp_pipeline_total_non_landed',
  'private_vacant_private_sector_business_park_space_vacant',
  'private_vacant_private_sector_multiple_user_factory_space_vacant',
  'private_vacant_private_sector_office_space_vacant',
  'private_vacant_private_sector_retail_space_vacant',
  'construction_material_cement_in_bulk_ordinary_portland_cement',
  'construction_material_concreting_sand',
  'construction_material_steel_reinforcement_bars_16_32mm_high_tensile',
  'construction_material_granite_20mm_aggregate',
  'construction_material_ready_mixed_concrete',
  'unit_labour_cost_construction',
  'demand_construction_materials_cement',
  'demand_construction_materials_granite',
  'demand_construction_materials_ready_mixed_concrete',
  'demand_construction_materials_steel_reinforcement_bars',
  'sgs_10y',
  'sgs_2y',
  'term_spread_10y_2y',
  'sora_overnight',
  'loan_bc_construction',
  'loan_bc_real_property',
  'loan_bc_total',
  'loan_limits_granted_building_construction',
  'loan_limits_utilised_building_construction',
  'construction_gdp'
];

const SERIES_MAJOR_CATEGORY_MAP = {
  commind_business_park_planned_others: 'A_pipeline_absorption',
  commind_business_park_planned_provisional_permission: 'A_pipeline_absorption',
  commind_business_park_planned_written_permission: 'A_pipeline_absorption',
  commind_business_park_total: 'A_pipeline_absorption',
  commind_business_park_under_construction: 'A_pipeline_absorption',
  commind_office_planned_others: 'A_pipeline_absorption',
  commind_office_planned_provisional_permission: 'A_pipeline_absorption',
  commind_office_planned_written_permission: 'A_pipeline_absorption',
  commind_office_total: 'A_pipeline_absorption',
  commind_office_under_construction: 'A_pipeline_absorption',
  commind_retail_planned_others: 'A_pipeline_absorption',
  commind_retail_planned_provisional_permission: 'A_pipeline_absorption',
  commind_retail_planned_written_permission: 'A_pipeline_absorption',
  commind_retail_total: 'A_pipeline_absorption',
  commind_retail_under_construction: 'A_pipeline_absorption',
  industrial_pipeline_others: 'A_pipeline_absorption',
  industrial_pipeline_provisional_permission: 'A_pipeline_absorption',
  industrial_pipeline_total: 'A_pipeline_absorption',
  industrial_pipeline_under_construction: 'A_pipeline_absorption',
  industrial_pipeline_written_permission: 'A_pipeline_absorption',
  prp_pipeline_non_landed_planned_others: 'A_pipeline_absorption',
  prp_pipeline_non_landed_planned_provisional_permission: 'A_pipeline_absorption',
  prp_pipeline_non_landed_planned_written_permission: 'A_pipeline_absorption',
  prp_pipeline_non_landed_under_construction: 'A_pipeline_absorption',
  prp_pipeline_total_non_landed: 'A_pipeline_absorption',
  private_vacant_private_sector_business_park_space_vacant: 'A_pipeline_absorption',
  private_vacant_private_sector_multiple_user_factory_space_vacant: 'A_pipeline_absorption',
  private_vacant_private_sector_office_space_vacant: 'A_pipeline_absorption',
  private_vacant_private_sector_retail_space_vacant: 'A_pipeline_absorption',
  construction_material_cement_in_bulk_ordinary_portland_cement: 'B_margin_pressures',
  construction_material_concreting_sand: 'B_margin_pressures',
  construction_material_steel_reinforcement_bars_16_32mm_high_tensile: 'B_margin_pressures',
  construction_material_granite_20mm_aggregate: 'B_margin_pressures',
  construction_material_ready_mixed_concrete: 'B_margin_pressures',
  unit_labour_cost_construction: 'B_margin_pressures',
  demand_construction_materials_cement: 'B_margin_pressures',
  demand_construction_materials_granite: 'B_margin_pressures',
  demand_construction_materials_ready_mixed_concrete: 'B_margin_pressures',
  demand_construction_materials_steel_reinforcement_bars: 'B_margin_pressures',
  sgs_10y: 'C_funding_credit',
  sgs_2y: 'C_funding_credit',
  term_spread_10y_2y: 'C_funding_credit',
  sora_overnight: 'C_funding_credit',
  loan_bc_construction: 'C_funding_credit',
  loan_bc_real_property: 'C_funding_credit',
  loan_bc_total: 'C_funding_credit',
  loan_limits_granted_building_construction: 'C_funding_credit',
  loan_limits_utilised_building_construction: 'C_funding_credit',
  construction_gdp: 'D_macro_regime'
};

function getMajorCategory(seriesId) {
  return SERIES_MAJOR_CATEGORY_MAP[seriesId] || null;
}

module.exports = {
  ALLOWED_MAJOR_CATEGORIES,
  MAJOR_CATEGORY_LABELS,
  EXPECTED_SERIES_IDS_49,
  SERIES_MAJOR_CATEGORY_MAP,
  getMajorCategory
};
